// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: urls.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls(id, created_at, updated_at, original_url, tiny_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, original_url, tiny_url
`

type CreateURLParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	OriginalUrl string
	TinyUrl     string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OriginalUrl,
		arg.TinyUrl,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalUrl,
		&i.TinyUrl,
	)
	return i, err
}
